### PR TITLE
Update to lts-13.27.

### PR DESCRIPTION
**Pull request by portnov**
The change is trivial.

### CODE REVIEW

**Comment by MichaelXavier** [comment]
Can you investigate these build failures?

**Comment by portnov** [comment]
ok, I will.

**Comment by portnov** [comment]
@MichaelXavier , do we still have to support lts-2, lts-3... lts-8 resolvers? I'd suggest to replace them with, for example, lts-10 ... lts-13.

**Comment by MichaelXavier** [comment]
@portnov we don't have to go back that far. Let's see if we can support the latest version of 10, 11, and so on.

**Comment by portnov** [comment]
@MichaelXavier , after updates to .travis.yml and .cabal file there are failed tests:

1) lts-10: https://travis-ci.org/Soostone/formattable/jobs/573159870

```
Failures:

  test/NumFormatSpec.hs:77: 

  1) NumFormat.formatNum switches to exponent notation for small numbers

       expected: "2.300e-3"

        but got: "0.002"

  test/NumFormatSpec.hs:113: 

  2) NumFormat.formatNum matches double-conversion

       Falsifiable (after 52 tests and 4 shrinks): 

       NumFormat {_nfUnits = 1000000.0, _nfPrefix = "$", _nfSuffix = "%", _nfThouSep = ",", _nfDecSep = ".", _nfStyle = Exponent, _nfPrec = Just (0,Decimals), _nfNegStyle = NegMinusSign}

       15.0

       "$1e-5%" /= "$2e-5%"

Randomized with seed 672491863

Finished in 0.0067 seconds

31 examples, 2 failures
```

2) lts-11: https://travis-ci.org/Soostone/formattable/jobs/573159871 

```
Failures:

  test/NumFormatSpec.hs:77: 

  1) NumFormat.formatNum switches to exponent notation for small numbers

       expected: "2.300e-3"

        but got: "0.002"

  test/NumFormatSpec.hs:113: 

  2) NumFormat.formatNum matches double-conversion

       Falsifiable (after 81 tests and 4 shrinks): 

       NumFormat {_nfUnits = 1000000.0, _nfPrefix = "$", _nfSuffix = "", _nfThouSep = "", _nfDecSep = ".", _nfStyle = Exponent, _nfPrec = Just (0,Decimals), _nfNegStyle = NegParens}

       15.0

       "$1e-5" /= "$2e-5"

Randomized with seed 1520966273

Finished in 0.0080 seconds

31 examples, 2 failures
```

3) lts-12: https://travis-ci.org/Soostone/formattable/jobs/573159872

```
Failures:

  test/NumFormatSpec.hs:77:11: 

  1) NumFormat.formatNum switches to exponent notation for small numbers

       expected: "2.300e-3"

        but got: "0.002"

  To rerun use: --match "/NumFormat/formatNum/switches to exponent notation for small numbers/"

  test/NumFormatSpec.hs:113:9: 

  2) NumFormat.formatNum matches double-conversion

       Falsifiable (after 78 tests and 5 shrinks):

         NumFormat {_nfUnits = 1000.0, _nfPrefix = "", _nfSuffix = "%", _nfThouSep = ",", _nfDecSep = ".", _nfStyle = SmartExponent 1 7, _nfPrec = Just (0,Decimals), _nfNegStyle = NegMinusSign}

         16.0

         "1e-2%" /= "2e-2%"

  To rerun use: --match "/NumFormat/formatNum/matches double-conversion/"

Randomized with seed 1134027458

Finished in 0.0086 seconds

31 examples, 2 failures
```

4) lts-13: https://travis-ci.org/Soostone/formattable/jobs/573159873

```
Failures:

  test/NumFormatSpec.hs:77:11: 

  1) NumFormat.formatNum switches to exponent notation for small numbers

       expected: "2.300e-3"

        but got: "0.002"

  To rerun use: --match "/NumFormat/formatNum/switches to exponent notation for small numbers/"

Randomized with seed 1217771871

Finished in 0.0080 seconds

31 examples, 1 failure
``` 

Do you have an idea how to fix it?

**Comment by portnov** [comment]
(huh, I knew something was going to go wrong the moment i wrote about the change being trivial...)

**Comment by MichaelXavier** [comment]
I cleaned up the PR a bit and merged it. Thanks!

**Pull request merged**
